FROM python:3

ENV PUTHONBUFFERED 1

RUN mkdir /opt/code
RUN mkdir /opt/requirements
WORKDIR /opt/code

ADD requirements /opt/requirements
RUN pip install --upgrade pip
RUN pip install -r /opt/requirements/production.txt
